[versions]
agp = "8.13.1"
kotlin = "2.2.21"
dependencyGuard = "0.5.0"
gradleVersionsPlugin = "0.53.0"

kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.9.0"

androidxCore = "1.17.0"
androidxLifecycle = "2.9.4"
androidxActivity = "1.11.0"
androidxBrowser = "1.9.0"
androidxComposeBom = "2025.11.00"
androidxNavigation = "2.9.6"
accompanist = "0.37.3"
material = "1.13.0"

ktlint = "1.8.0"

[libraries]
kotlinxCoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinxSerializationCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
androidxCore = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidxLifecycleRuntime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidxLifecycleProcess = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidxLifecycle" }
androidxLifecycleViewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidxBrowser = { group = "androidx.browser", name = "browser", version.ref = "androidxBrowser" }
androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidxComposeUi = { group = "androidx.compose.ui", name = "ui" }
androidxComposeUiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidxComposeUiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidxComposeUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidxComposeUiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidxComposeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
androidxComposeMaterialIconsCore = { group = "androidx.compose.material", name = "material-icons-core" }
androidxNavigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
accompanistDrawablePainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }
accompanistPermissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

ktlint = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }
